#!/usr/bin/env python3
"""Build repository-local Persona 5 Royal Shadow and negotiation datasets.

Sources:
- https://github.com/joyce-chen/persona5-negotiation/blob/master/shadows_royal.md
- https://github.com/joyce-chen/persona5-negotiation/blob/master/royal.md

The generated ES modules are consumed by GitHub Pages; the website performs no
runtime requests to the source site.
"""

from __future__ import annotations

import html
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
SHADOWS_OUTPUT = DATA_DIR / "shadows-royal.js"
NEGOTIATION_OUTPUT = DATA_DIR / "negotiation-royal.js"
REPORT_OUTPUT = DATA_DIR / "negotiation-report.json"

SHADOWS_URL = "https://raw.githubusercontent.com/joyce-chen/persona5-negotiation/master/shadows_royal.md"
NEGOTIATION_URL = "https://raw.githubusercontent.com/joyce-chen/persona5-negotiation/master/royal.md"
USER_AGENT = "Persona-5-Wiki repository data sync/1.0"

TAG_RE = re.compile(r"<[^>]+>")
COMMENT_RE = re.compile(r"<!--.*?-->", re.S)
ROW_RE = re.compile(r"<tr\b[^>]*>(.*?)</tr>", re.I | re.S)
CELL_RE = re.compile(r"<(t[dh])\b([^>]*)>(.*?)</t[dh]>", re.I | re.S)
TABLE_RE = re.compile(r"<table\b([^>]*)>(.*?)</table>", re.I | re.S)
ROYAL_BADGE_RE = re.compile(r"<span\b[^>]*class\s*=\s*(['\"])[^'\"]*badge-danger[^'\"]*\1[^>]*>.*?</span>", re.I | re.S)


def download(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=90) as response:
        return response.read().decode("utf-8")


def clean_text(value: str) -> str:
    value = re.sub(r"<br\s*/?>", " ", value, flags=re.I)
    value = TAG_RE.sub("", value)
    value = html.unescape(value)
    value = re.sub(r"\s+", " ", value).strip()
    return value


def write_module(path: Path, export_name: str, data: object, source: str) -> None:
    content = (
        f"// Generated by scripts/sync_negotiation_data.py. Do not edit manually.\n"
        f"// Source: {source}\n"
        f"export const {export_name} = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )
    path.write_text(content, encoding="utf-8")


def parse_shadows(source: str) -> list[dict[str, object]]:
    source = COMMENT_RE.sub("", source)
    headings = list(re.finditer(r"(?m)^#####\s+(.+?)\s*$", source))
    rows: list[dict[str, object]] = []

    for index, heading in enumerate(headings):
        section_end = headings[index + 1].start() if index + 1 < len(headings) else len(source)
        location = clean_text(heading.group(1))
        section = source[heading.end() : section_end]
        category = "Mementos" if "Mementos" in location else "Palace"
        if "Qliphoth" in location:
            category = "Qliphoth"

        for _, table_body in TABLE_RE.findall(section):
            parsed_rows = ROW_RE.findall(table_body)
            if not parsed_rows:
                continue

            headers = [clean_text(cell[2]) for cell in CELL_RE.findall(parsed_rows[0])]
            if not headers or "Persona" not in headers or "Shadow" not in headers:
                continue

            for raw_row in parsed_rows[1:]:
                cells = CELL_RE.findall(raw_row)
                values = [clean_text(cell[2]) for cell in cells]
                if len(values) < 6:
                    continue
                raw_persona = cells[1][2]
                persona_name = clean_text(ROYAL_BADGE_RE.sub("", raw_persona))
                mapping = dict(zip(headers, values))
                mapping["Persona"] = persona_name
                level_value = mapping.get("Level", values[0])
                level: int | str
                try:
                    level = int(level_value)
                except ValueError:
                    level = level_value

                record = {
                    "location": location,
                    "category": category,
                    "level": level,
                    "persona": mapping.get("Persona", ""),
                    "shadow": mapping.get("Shadow", ""),
                    "arcana": mapping.get("Arcana", ""),
                    "personality": mapping.get("Personality", ""),
                    "areas": mapping.get("Areas", ""),
                    "weakness": mapping.get("Weakness", ""),
                    "royal": "badge-danger" in raw_persona or "Royal" in location or "Da’at" in location,
                    "treasure": "Treasure Demon" in mapping.get("Shadow", ""),
                }
                if record["persona"] and record["shadow"]:
                    rows.append(record)

    if len(rows) < 180:
        raise RuntimeError(f"Shadow extraction coverage is unexpectedly low: {len(rows)} rows")
    return rows


def attribute_value(attributes: str, name: str) -> str:
    match = re.search(rf"\b{name}\s*=\s*(['\"])(.*?)\1", attributes, re.I | re.S)
    return match.group(2) if match else ""


def parse_negotiations(source: str) -> list[dict[str, object]]:
    source = COMMENT_RE.sub("", source)
    questions: list[dict[str, object]] = []
    personalities = ["gloomy", "irritable", "timid", "upbeat"]

    for table_attributes, table_body in TABLE_RE.findall(source):
        classes = attribute_value(table_attributes, "class").split()
        if "filterDiv" not in classes:
            continue

        question_match = re.search(r"<th\b[^>]*colspan\s*=\s*['\"]?5['\"]?[^>]*>(.*?)</th>", table_body, re.I | re.S)
        if not question_match:
            continue
        question = clean_text(question_match.group(1))
        if not question:
            continue

        shadow_classes = classes[classes.index("filterDiv") + 1 :]
        shadows = [value.replace("_", " ") for value in shadow_classes if value and value != "None"]
        answer_rows: list[dict[str, object]] = []

        for raw_row in ROW_RE.findall(table_body):
            cells = CELL_RE.findall(raw_row)
            if len(cells) != 5 or cells[0][0].lower() != "td":
                continue
            answer = clean_text(cells[0][2])
            if not answer:
                continue

            reactions: dict[str, dict[str, object]] = {}
            for personality, cell in zip(personalities, cells[1:]):
                attributes = cell[1]
                value_match = re.search(r"<div\b[^>]*class\s*=\s*['\"]text['\"][^>]*>(.*?)</div>", cell[2], re.I | re.S)
                value = clean_text(value_match.group(1)) if value_match else clean_text(cell[2])
                value = value.upper() if value else "-"
                reactions[personality] = {
                    "value": value,
                    "confirmed": "unconfirmed" not in attributes.lower(),
                }

            answer_rows.append({"text": answer, "reactions": reactions})

        if answer_rows:
            questions.append({"question": question, "shadows": shadows, "answers": answer_rows})

    if len(questions) < 250:
        raise RuntimeError(f"Negotiation extraction coverage is unexpectedly low: {len(questions)} questions")
    return questions


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    shadows_source = download(SHADOWS_URL)
    negotiation_source = download(NEGOTIATION_URL)

    shadows = parse_shadows(shadows_source)
    questions = parse_negotiations(negotiation_source)

    write_module(SHADOWS_OUTPUT, "royalShadows", shadows, SHADOWS_URL)
    write_module(NEGOTIATION_OUTPUT, "royalNegotiations", questions, NEGOTIATION_URL)

    report = {
        "sourceRepository": "joyce-chen/persona5-negotiation",
        "shadowRows": len(shadows),
        "uniquePersonas": len({row["persona"] for row in shadows}),
        "locations": len({row["location"] for row in shadows}),
        "negotiationQuestions": len(questions),
        "answerRows": sum(len(question["answers"]) for question in questions),
        "linkedShadows": len({shadow for question in questions for shadow in question["shadows"]}),
    }
    REPORT_OUTPUT.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
