#!/usr/bin/env python3
"""Build repository-local Persona 5 Royal Fusion DB datasets.

Data source:
https://github.com/aqiu384/megaten-fusion-tool/tree/f7d41c3f947a232d41bd8272de4221eb55f721c8/src/app/p5/data

The generated ES modules are consumed locally by GitHub Pages. The deployed site
performs no runtime requests to aqiu384.github.io or the source repository.
"""

from __future__ import annotations

import json
import math
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
SOURCE_COMMIT = "f7d41c3f947a232d41bd8272de4221eb55f721c8"
BASE_URL = (
    "https://raw.githubusercontent.com/aqiu384/megaten-fusion-tool/"
    f"{SOURCE_COMMIT}/src/app/p5/data"
)
SKILL_EFFECTS_URL = (
    "https://raw.githubusercontent.com/aqiu384/megaten-fusion-tool/"
    f"{SOURCE_COMMIT}/src/app/compendium/data/skill-effects.json"
)
USER_AGENT = "Persona-5-Wiki repository Fusion DB sync/1.0"

FILES = {
    "config": "comp-config.json",
    "personas": "roy-demon-data.json",
    "party": "roy-party-data.json",
    "skills": "roy-skill-data.json",
    "enemies": "roy-enemy-data.json",
    "unlocks": "roy-demon-unlocks.json",
    "special": "roy-special-recipes.json",
    "prereqs": "roy-fusion-prereqs.json",
    "chart": "roy-fusion-chart.json",
    "elements": "roy-element-chart.json",
}

RESIST_LABELS = {
    "w": "wk", "W": "wk", "x": "wk", "z": "wk",
    "-": "no", "A": "no", "a": "no",
    "s": "rs", "S": "rs",
    "n": "nu", "N": "nu", "_": "nu",
    "r": "rp", "R": "rp",
    "d": "dr", "D": "dr",
}


def download_json(url: str) -> Any:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=120) as response:
        return json.load(response)


def write_module(filename: str, export_name: str, value: Any, source_note: str) -> None:
    path = DATA_DIR / filename
    content = (
        "// Generated by scripts/sync_aqiu_p5r_data.py. Do not edit manually.\n"
        f"// Source: {source_note}\n"
        f"export const {export_name} = "
        + json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    path.write_text(content, encoding="utf-8")


def decode_resists(code: str, elements: list[str]) -> dict[str, str]:
    padded = (code or "").ljust(len(elements), "-")
    return {element: RESIST_LABELS.get(char, "no") for element, char in zip(elements, padded)}


def summon_price(stats: list[int]) -> int:
    return 2000 + sum(stats) ** 2


def format_cost(raw: int) -> str:
    if not raw:
        return "Auto"
    if 1000 <= raw < 2000:
        return f"{raw - 1000} SP"
    if raw >= 2000:
        return f"{raw - 2000} special"
    return f"{raw}% HP"


def skill_effect(numbers: list[int], descriptions: list[str], templates: dict[str, str]) -> str:
    rank, _cost, power, min_hits, max_hits, accuracy, crit, modifier = numbers
    del rank
    effect, condition, _card = descriptions
    base_modifier = int(modifier)
    shown_modifier: int | float = base_modifier if base_modifier < 1000 else (base_modifier - 1000) / 100
    parts: list[str] = []
    if power:
        parts.append(f"√{power} pwr")
    if min_hits != max_hits:
        parts.append(f"{min_hits}-{max_hits} hits")
    elif max_hits >= 2:
        parts.append(f"{max_hits} hits")
    if accuracy and not 90 <= accuracy <= 110:
        parts.append(f"{accuracy}% acc")
    if crit > 5:
        parts.append(f"{crit}% crit")
    if condition != "-":
        template = templates.get(condition[3:], condition) if condition.startswith("FMT") else condition
        rendered = template.replace("$1", str(shown_modifier)).replace("$2", effect)
        if rendered:
            parts.append(rendered)
    text = ", ".join(part for part in parts if part)
    return text[:1].upper() + text[1:] if text else "-"


def build_unlock_lookup(groups: list[dict[str, Any]], prereqs: dict[str, str]) -> dict[str, dict[str, str]]:
    lookup: dict[str, dict[str, str]] = {
        name: {"category": "Recruitment", "condition": condition}
        for name, condition in prereqs.items()
    }
    for group in groups:
        category = group.get("category", "Unlock")
        for names, condition in group.get("conditions", {}).items():
            for name in names.split(","):
                lookup[name] = {"category": category, "condition": condition}
    return lookup


def build_personas(
    persona_json: dict[str, Any],
    party_json: dict[str, Any],
    config: dict[str, Any],
    special: dict[str, list[str]],
    unlock_lookup: dict[str, dict[str, str]],
) -> list[dict[str, Any]]:
    elements = config["resistElems"]
    rows: list[dict[str, Any]] = []
    for is_party, source in ((False, persona_json), (True, party_json)):
        for name, item in source.items():
            stats = item.get("stats", [])
            recipe = special.get(name)
            fusion_type = item.get("fusion", "party" if is_party else "normal")
            if recipe is not None:
                fusion_type = "special" if recipe else "treasure"
            unlock = unlock_lookup.get(name)
            learned = [
                {"name": skill, "level": level}
                for skill, level in item.get("skills", {}).items()
            ]
            learned.sort(key=lambda entry: (0 if isinstance(entry["level"], float) and entry["level"] < 1 else entry["level"], entry["name"]))
            rows.append({
                "name": name,
                "level": item.get("lvl", 0),
                "arcana": item.get("race", ""),
                "inherits": item.get("inherits", item.get("inherit", "")),
                "trait": item.get("trait", ""),
                "price": 0 if is_party else summon_price(stats),
                "stats": dict(zip(config["baseStats"], stats)),
                "maxStats": dict(zip(config["baseStats"], item.get("statsm", []))) if item.get("statsm") else None,
                "resists": decode_resists(item.get("resists", ""), elements),
                "secondResists": decode_resists(item.get("sesists", ""), elements) if item.get("sesists") else None,
                "skills": learned,
                "item": item.get("item", ""),
                "itemRoyal": item.get("itemr", ""),
                "fusionType": fusion_type,
                "recipe": recipe or [],
                "party": is_party,
                "unlockCategory": unlock.get("category", "") if unlock else "",
                "unlockCondition": unlock.get("condition", "") if unlock else "",
                "dlc": bool(unlock and unlock.get("category") == "Downloadable Content"),
            })
    rows.sort(key=lambda row: (row["level"], row["arcana"], row["name"]))
    return rows


def build_skills(
    raw_skills: dict[str, Any],
    personas: list[dict[str, Any]],
    effects: dict[str, str],
) -> list[dict[str, Any]]:
    learners: dict[str, list[dict[str, Any]]] = {}
    for persona in personas:
        for skill in persona["skills"]:
            learners.setdefault(skill["name"], []).append({"name": persona["name"], "level": skill["level"]})
    rows: list[dict[str, Any]] = []
    for code, row in raw_skills.items():
        name, element, target = row["a"]
        numbers = row["b"]
        descriptions = row["c"]
        rows.append({
            "code": code,
            "name": name,
            "element": element,
            "target": "Self" if target == "-" else target,
            "rank": numbers[0] or 99,
            "cost": format_cost(numbers[1]),
            "power": numbers[2],
            "accuracy": numbers[5],
            "crit": numbers[6],
            "effect": skill_effect(numbers, descriptions, effects),
            "card": "" if descriptions[2] == "-" else descriptions[2],
            "unique": numbers[0] >= 90,
            "learnedBy": sorted(learners.get(name, []), key=lambda entry: (entry["level"] if isinstance(entry["level"], int) else 0, entry["name"])),
        })
    rows.sort(key=lambda row: (row["element"], row["rank"], row["name"]))
    return rows


def build_enemies(raw: dict[str, Any], config: dict[str, Any]) -> list[dict[str, Any]]:
    elements = config["resistElems"]
    rows = []
    for name, item in raw.items():
        stats = item.get("stats", [])
        drops = []
        for field in ("material", "armor", "card"):
            value = item.get(field)
            if value and value != "-":
                drops.append(value)
        drops.extend(item.get("drops", []))
        rows.append({
            "name": name,
            "persona": item.get("persona", ""),
            "level": item.get("lvl", 0),
            "arcana": item.get("race", ""),
            "personality": item.get("trait", ""),
            "area": item.get("areas", item.get("area", "")),
            "exp": item.get("exp", 0),
            "yen": item.get("yen", item.get("price", 0)),
            "hp": stats[0] if len(stats) > 0 else 0,
            "mp": stats[1] if len(stats) > 1 else 0,
            "stats": dict(zip(config["baseStats"], stats[2:7])),
            "resists": decode_resists(item.get("resists", ""), elements),
            "skills": item.get("skills", []),
            "drops": list(dict.fromkeys(drops)),
        })
    rows.sort(key=lambda row: (row["level"], row["name"]))
    return rows


def build_fusion_data(
    config: dict[str, Any],
    chart: dict[str, Any],
    element_chart: dict[str, Any],
    special: dict[str, list[str]],
    unlocks: list[dict[str, Any]],
    source_commit: str,
) -> dict[str, Any]:
    return {
        "sourceCommit": source_commit,
        "resistElements": config["resistElems"],
        "inheritElements": config["inheritElems"],
        "arcana": chart["races"],
        "normalChart": chart["table"],
        "treasureDemons": element_chart["elems"],
        "elementArcana": element_chart["races"],
        "elementModifiers": element_chart["table"],
        "specialRecipes": special,
        "unlockGroups": unlocks,
        "levelModifier": 0.5,
    }


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    raw = {key: download_json(f"{BASE_URL}/{filename}") for key, filename in FILES.items()}
    effects = download_json(SKILL_EFFECTS_URL)
    unlock_lookup = build_unlock_lookup(raw["unlocks"], raw["prereqs"])
    personas = build_personas(raw["personas"], raw["party"], raw["config"], raw["special"], unlock_lookup)
    skills = build_skills(raw["skills"], personas, effects)
    enemies = build_enemies(raw["enemies"], raw["config"])
    fusion = build_fusion_data(raw["config"], raw["chart"], raw["elements"], raw["special"], raw["unlocks"], SOURCE_COMMIT)

    write_module("aqiu-p5r-personas.js", "aqiuP5rPersonas", personas, f"aqiu384/megaten-fusion-tool@{SOURCE_COMMIT}")
    write_module("aqiu-p5r-skills.js", "aqiuP5rSkills", skills, f"aqiu384/megaten-fusion-tool@{SOURCE_COMMIT}")
    write_module("aqiu-p5r-enemies.js", "aqiuP5rEnemies", enemies, f"aqiu384/megaten-fusion-tool@{SOURCE_COMMIT}")
    write_module("aqiu-p5r-fusion.js", "aqiuP5rFusion", fusion, f"aqiu384/megaten-fusion-tool@{SOURCE_COMMIT}")

    report = {
        "sourceCommit": SOURCE_COMMIT,
        "personas": len(personas),
        "fusionPersonas": sum(not row["party"] for row in personas),
        "partyPersonas": sum(row["party"] for row in personas),
        "skills": len(skills),
        "enemies": len(enemies),
        "arcana": len(fusion["arcana"]),
        "specialRecipes": len(raw["special"]),
        "unlockGroups": len(raw["unlocks"]),
    }
    (DATA_DIR / "aqiu-p5r-report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
